# Generated by Django 4.2.5 on 2023-09-29 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_alter_userprofile_role_alter_userprofile_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('graduate', models.CharField(choices=[('GRADUATED', 'Graduated'), ('ONGOING', 'Ongoing')], max_length=200)),
                ('program', models.CharField(choices=[('BS COMPUTER SCIENCE', 'BS Computer Science'), ('BS BIOCHEMISTRY', 'BS Biochemistry'), ('BS APPLIED PHYSICS', 'BS Applied Physics')], max_length=200)),
                ('enrollment', models.CharField(choices=[('ENROLLED', 'Currently Enrolled'), ('MISSING', 'Not Enrolled'), ('LEAVE OF ABSENCE', 'Leave of Absence')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='Rencio', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='Simangan', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('ADVISOR', 'Advisor'), ('NON ADVISOR FACULTY', 'Professor')], max_length=50),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=200)),
                ('subject_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.offeredsubject')),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.term')),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_units', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.offeredsubject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.userprofile'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion', models.CharField(choices=[('PASSED', 'Passed'), ('INCOMPLETE', 'Incomplete'), ('FAILED', 'Failed')], max_length=200)),
                ('grade', models.IntegerField(choices=[(1, '1.0'), (1.25, '1.25'), (1.5, '1.5'), (1.75, '1.75'), (2.0, '2.0'), (2.25, '2.25'), (2.5, '2.5'), (2.75, '2.75'), (3, '3.0'), (4, '4.0'), (5, '5.0'), (0, 'INC')])),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.subject')),
            ],
        ),
    ]
