# Generated by Django 4.2.5 on 2023-09-29 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_alter_term_end_date_alter_term_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.userprofile'),
        ),
    ]
