# Generated by Django 4.2.5 on 2023-09-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_alter_subject_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplanrecord',
            name='required_units',
            field=models.IntegerField(default=148),
            preserve_default=False,
        ),
    ]
