# Generated by Django 4.2.5 on 2023-09-30 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_remove_studyplanrecord_required_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='term',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
