# Generated by Django 4.2.5 on 2023-10-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0013_alter_student_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
