# Generated by Django 4.2.5 on 2023-10-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0017_alter_registration_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredsubject',
            name='subject_title',
            field=models.CharField(default='Human Computer Interaction', max_length=200),
            preserve_default=False,
        ),
    ]
