# Generated by Django 4.2.5 on 2023-10-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0018_offeredsubject_subject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.FloatField(choices=[(1, '1.0'), (1.25, '1.25'), (1.5, '1.5'), (1.75, '1.75'), (2.0, '2.0'), (2.25, '2.25'), (2.5, '2.5'), (2.75, '2.75'), (3, '3.0'), (4, '4.0'), (5, '5.0'), (0, 'INC')], default=0),
        ),
    ]
