# Generated by Django 4.2.5 on 2023-12-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0022_registration_graded_student_completed_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='units',
        ),
        migrations.AddField(
            model_name='offeredsubject',
            name='lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offeredsubject',
            name='lecture',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offeredsubject',
            name='units',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_code',
            field=models.CharField(default='placeholder CC', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.FloatField(choices=[(1, '1.0'), (1.25, '1.25'), (1.5, '1.5'), (1.75, '1.75'), (2.0, '2.0'), (2.25, '2.25'), (2.5, '2.5'), (2.75, '2.75'), (3, '3.0'), (5, '5.0'), (0, 'INC')], default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('THESIS ADVISOR', 'Thesis Advisor'), ('PROGRAM ADVISOR', 'Program Advisor'), ('FACULTY', 'Faculty')], max_length=50),
        ),
    ]
