# Generated by Django 4.2.5 on 2023-12-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0024_userprofile_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='staff_id',
            field=models.CharField(default='placeholderID 123', max_length=15),
            preserve_default=False,
        ),
    ]
