# Generated by Django 4.2.5 on 2023-12-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0026_alter_registration_completion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gwa',
            field=models.IntegerField(default=0),
        ),
    ]
