# Generated by Django 4.2.5 on 2023-12-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0027_student_gwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_grade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='gwa',
            field=models.FloatField(default=0),
        ),
    ]
