# Generated by Django 4.2.5 on 2023-12-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0028_student_total_grade_alter_student_gwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.userprofile'),
        ),
    ]
