# Generated by Django 4.2.5 on 2023-12-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0033_alter_offeredsubject_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredsubject',
            name='department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offeredsubject',
            name='subject_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offeredsubject',
            name='subject_title',
            field=models.CharField(max_length=200),
        ),
    ]
