# Generated by Django 4.2.5 on 2023-12-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0034_alter_offeredsubject_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='graded',
        ),
    ]
