# Generated by Django 4.2.5 on 2023-12-09 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0035_remove_registration_graded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment',
            field=models.CharField(choices=[('ENROLLED', 'Registered'), ('UNENROLLED', 'Not Registered'), ('LEAVE OF ABSENCE', 'Leave of Absence')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_term', to='login_app.term'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recent_term', to='login_app.term'),
        ),
    ]
