# Generated by Django 5.0.1 on 2024-01-06 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0036_alter_student_enrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.student'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_app.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_offered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_app.offeredsubject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_app.term'),
        ),
    ]
